from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from datetime import datetime

class PDFReportService:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.styles.add(ParagraphStyle(name='SectionHeader', fontSize=14, leading=16, spaceAfter=10, textColor=colors.darkblue, fontName='Helvetica-Bold'))
        self.styles.add(ParagraphStyle(name='NormalSmall', parent=self.styles['Normal'], fontSize=9, leading=11))

    def generate_report(self, project_data: dict) -> BytesIO:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        elements = []

        # Extract Data
        project_name = project_data.get("name", "Untitled")
        location = project_data.get("location_address", "Unknown Location")
        input_data = project_data.get("data", {}).get("input", {})
        result_data = project_data.get("data", {}).get("result", {})
        
        # --- HEADER ---
        elements.append(Paragraph(f"Basis of Design: Fire Alarm System", self.styles['Title']))
        elements.append(Spacer(1, 12))
        
        # Project Info Table
        info_data = [
            ["Project Name:", project_name],
            ["Location:", location],
            ["Date generated:", datetime.now().strftime("%Y-%m-%d %H:%M")],
            ["Occupancy:", input_data.get("occupancy", "N/A")],
            ["Building Stats:", f"{input_data.get('sqft', 0)} SqFt | {input_data.get('num_stories', 0)} Stories | {input_data.get('num_units', 0)} Units"]
        ]
        t_info = Table(info_data, colWidths=[120, 350])
        t_info.setStyle(TableStyle([
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
            ('BACKGROUND', (0,0), (0,-1), colors.whitesmoke),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(t_info)
        elements.append(Spacer(1, 24))

        # --- EXECUTIVE SUMMARY ---
        elements.append(Paragraph("1. Executive Summary", self.styles['SectionHeader']))
        sys_type = result_data.get("system_type", "Analysis Required")
        summary_text = (
            f"Based on the analysis of building parameters, the required system type is: <b>{sys_type}</b>. "
            f"This design complies with NFPA 72, NFPA 101, and Florida Building Code (7th Ed)."
        )
        elements.append(Paragraph(summary_text, self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # --- COMPLIANCE NOTES ---
        elements.append(Paragraph("2. Compliance & Logic Audit", self.styles['SectionHeader']))
        notes = result_data.get("compliance_notes", [])
        if notes:
            for note in notes:
                # Color code critical notes
                style = self.styles['Normal']
                if "REQUIRED" in note:
                    note = f"<font color='red'><b>[CRITICAL]</b></font> {note}"
                elements.append(Paragraph(f"• {note}", style))
                elements.append(Spacer(1, 4))
        else:
            elements.append(Paragraph("No specific compliance flags detected.", self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # --- BILL OF MATERIALS (BOM) ---
        elements.append(Paragraph("3. Preliminary Bill of Materials", self.styles['SectionHeader']))
        
        bom_data = [["Item Description", "Category"]]
        
        # Tier A (Headend)
        for item in result_data.get("bom_tier_a", []):
            bom_data.append([item, "Headend / Control"])
            
        # Tier B (Field)
        for item in result_data.get("bom_tier_b", []):
            bom_data.append([item, "Notification / Field"])
            
        t_bom = Table(bom_data, colWidths=[350, 120])
        t_bom.setStyle(TableStyle([
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
            ('ROWBACKGROUNDS', (1,0), (-1,-1), [colors.white, colors.whitesmoke]),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(t_bom)

        elements.append(Spacer(1, 36))
        elements.append(Paragraph("Generated by Cicuma Fire Brain v2.1", self.styles['NormalSmall']))

        doc.build(elements)
        buffer.seek(0)
        return buffer
